server:
    port: 8080

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: ds055862.mongolab.com
            port: 55862
            database: heroku_0bftrxqk
            username: jobninja
            password: asdqwe
    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhtest

http:
    cache:
        timeToLiveInDays: 31


