server:
    port: 8080

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            database: jhtest
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: 678655644001-m6db8qpgo5mlc8chvp668pdgop898eht.apps.googleusercontent.com
            clientSecret: secret
        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: 1536612453318137
            clientSecret: secret
        # see https://apps.twitter.com/app/
        twitter:
            clientId: K1y8RXFFZje68FSG3mV7PIQzQ
            clientSecret: secret

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhtest

mail:
    host: smtp.gmail.com
    port: 587
    username: job.ninja.noreply@gmail.com
    password: jobninja3322
    protocol: smtp
    tls: true
    auth: true
    from: job.ninja.noreply@gmail.com

aws.s3.bucketName: job-ninja-assets-dev
