liquibase:
    context: prod

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: ds055862.mongolab.com
            port: 55862
            database: heroku_0bftrxqk
            username: jobninja
            password: asdqwe
    thymeleaf:
        mode: XHTML
        cache: true
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: 678655644001-m6db8qpgo5mlc8chvp668pdgop898eht.apps.googleusercontent.com
            clientSecret: secret

        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: 1535817236730992
            clientSecret: secret

        # see https://apps.twitter.com/app/
        twitter:
            clientId: wmOzmnemRtJK2dDiF0bpfc3ea
            clientSecret: secret

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhtest

http:
    cache:
        timeToLiveInDays: 31

mail:
    host: smtp.mailgun.org
    port: 587
    username: postmaster@app60b1eb3b6b6f4e1cb5f541422010abda.mailgun.org
    password:
    protocol: smtp
    tls: true
    auth: true
    from: postmaster@app60b1eb3b6b6f4e1cb5f541422010abda.mailgun.org

aws.s3.bucketName: job-ninja-assets
